# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'xmppDemo' do
pod 'XMPPFramework', :podspec => 'https://raw.githubusercontent.com/andrey-justo-movile/XMPPFramework/3.7.2/XMPPFramework.podspec.json'
end

target 'xmppDemoTests' do
pod 'XMPPFramework', :podspec => 'https://raw.githubusercontent.com/andrey-justo-movile/XMPPFramework/3.7.2/XMPPFramework.podspec.json'
end

target 'xmppDemoUITests' do
pod 'XMPPFramework', :podspec => 'https://raw.githubusercontent.com/andrey-justo-movile/XMPPFramework/3.7.2/XMPPFramework.podspec.json'
end

